name: sanitize_dom
description: >
  This package provides useful utilities for working with the DOM
  validation and sanitization.
version: 0.0.8
repository: https://github.com/ykmnkmi/sanitize_dom.dart
issue_tracker: https://github.com/ykmnkmi/sanitize_dom.dart/issues

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  lints: ^5.1.0
  test: ^1.25.15
