name: sanitize_dom
description: An absolute bare-bones web app.
version: 0.0.1
# repository: https://github.com/ykmnkmi/sanitize_dom.dart

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  lints: ^5.1.0
